# Generated by Django 5.2 on 2025-04-23 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('tipo', models.CharField(choices=[('noticia', 'Site de Notícias'), ('blog', 'Blog'), ('forum', 'Fórum'), ('rede_social', 'Rede Social'), ('outro', 'Outro')], max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fonte',
                'verbose_name_plural': 'Fontes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=100, unique=True)),
                ('categoria', models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundária'), ('monitoramento', 'Monitoramento'), ('alerta', 'Alerta')], max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta'), (4, 'Crítica')], default=2)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Palavra-chave',
                'verbose_name_plural': 'Palavras-chave',
                'ordering': ['-prioridade', 'string'],
            },
        ),
        migrations.CreateModel(
            name='EntradaColetada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(blank=True, null=True)),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('link_relacionado', models.URLField(max_length=255)),
                ('processado', models.BooleanField(default=False)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='scraper.fonte')),
                ('palavras_chave', models.ManyToManyField(related_name='entradas', to='scraper.palavrachave')),
            ],
            options={
                'verbose_name': 'Entrada Coletada',
                'verbose_name_plural': 'Entradas Coletadas',
                'ordering': ['-data_coleta'],
                'indexes': [models.Index(fields=['-data_coleta'], name='scraper_ent_data_co_c0325b_idx'), models.Index(fields=['processado'], name='scraper_ent_process_d7f040_idx')],
            },
        ),
    ]
